# Generated by Django 5.1.3 on 2024-12-03 04:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DSA', '0002_customuser_contact_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='is_verified',
            new_name='otp_verified',
        ),
        migrations.AddField(
            model_name='otp',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 3, 5, 1, 36, 844695, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['user', 'otp_code'], name='DSA_otp_user_id_b7857e_idx'),
        ),
    ]
