# Generated by Django 5.1.3 on 2024-12-04 09:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DSA', '0003_rename_is_verified_otp_otp_verified_otp_expired_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='roll_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 4, 9, 12, 29, 878963, tzinfo=datetime.timezone.utc)),
        ),
    ]
