# Generated by Django 5.1.3 on 2024-12-05 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DSA', '0006_alter_otp_expired_at_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 5, 13, 58, 56, 623591, tzinfo=datetime.timezone.utc)),
        ),
    ]
