# Generated by Django 5.1.3 on 2024-12-05 15:19

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DSA', '0007_alter_otp_expired_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 5, 15, 24, 37, 320429, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('header_background', models.ImageField(blank=True, null=True, upload_to='header_backgrounds/')),
                ('certificates', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
