# Generated by Django 5.1.3 on 2024-12-06 03:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DSA', '0008_alter_otp_expired_at_userprofile_delete_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 6, 3, 18, 27, 107318, tzinfo=datetime.timezone.utc)),
        ),
    ]
