# Generated by Django 5.1.3 on 2024-12-06 05:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DSA', '0009_alter_otp_expired_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('performance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mcqs', models.PositiveIntegerField()),
                ('attendance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('practical', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AlterField(
            model_name='otp',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 6, 5, 56, 40, 375746, tzinfo=datetime.timezone.utc)),
        ),
    ]
