# Generated by Django 5.1.3 on 2024-12-06 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DSA', '0011_rename_studentperformance_studentresult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='batch',
            field=models.CharField(choices=[('A', 'Batch A'), ('B', 'Batch B'), ('C', 'Batch C')], default='A', max_length=10),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 6, 7, 44, 29, 314214, tzinfo=datetime.timezone.utc)),
        ),
    ]
