# Generated by Django 5.1.3 on 2024-12-06 07:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DSA', '0012_studentresult_batch_alter_otp_expired_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 6, 7, 58, 11, 735429, tzinfo=datetime.timezone.utc)),
        ),
    ]
