# Generated by Django 5.1.3 on 2024-12-06 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DSA', '0014_remove_studentresult_total_alter_otp_expired_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='practical_no',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 6, 8, 57, 54, 641086, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='mcqs',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
