# Generated by Django 5.1.3 on 2024-12-06 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DSA', '0015_studentresult_practical_no_alter_otp_expired_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 6, 9, 18, 39, 94048, tzinfo=datetime.timezone.utc)),
        ),
    ]
