# Generated by Django 5.1.3 on 2024-12-06 09:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DSA', '0016_alter_otp_expired_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentresult',
            name='practical',
        ),
        migrations.AlterField(
            model_name='otp',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 6, 9, 49, 25, 10079, tzinfo=datetime.timezone.utc)),
        ),
    ]
