# Generated by Django 5.1.3 on 2024-12-15 04:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DSA', '0017_remove_studentresult_practical_alter_otp_expired_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 15, 4, 20, 45, 390541, tzinfo=datetime.timezone.utc)),
        ),
    ]
