# Generated by Django 5.1.3 on 2024-12-15 06:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DSA', '0018_alter_otp_expired_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='stream',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 15, 6, 6, 39, 716161, tzinfo=datetime.timezone.utc)),
        ),
    ]
